language: node_js
cache:
  directories:
    - $HOME/.npm
node_js:
  - lts/*

after_success:
    - test "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" = "false" && \
      sh .travis/deploy_heroku.sh
