language: node_js
cache:
  directories:
  - "$HOME/.npm"
node_js:
- lts/*
notifications:
  email:
    on_success: never
deploy:
  provider: heroku
  api_key:
    secure: nT4u3fJATl5ZgGvG0yPXYJjmtBJdT03m097GBj7HsEkRU3XvO0/2SKav3lG7FphIJ5qcFIUimmc1x1sn9ucRaueYqKPzHfCQTQovMR+ti7z9LkOtZt5dbGiH2jyBjMc/BZktXrVo282DWdS75iQbiQrjkmyIxy1/dZ+qXMPPWcD9uCQKcWHnP118+v04u/UZqM332+wEEWd+xMk6GOuJpOrjXgU6venu9tP9nlleIN5vFXK0YsW7agMj4SiRiScKR/h5acDPslYNOI7+i/mT4UcVJvKEDa8z5HXe+ZcOpGDfpMK5UZ9zO2vl2WfmJHK8r3MBJvQG8bG3nIBnrMQHMSyZhWsIKjV269BRD5MNmbeXWzvQ9cqy7UZ20LEqH/khWaewwf3LtgGqVl92LWcSO763W5Z/YMaN+JhaRVwvKmsZBWtUTg2MenVplwDy9OueKmKxzE6DWIxK251HDCOUNx8+eiyrhILgFhsCVmmQ+lWbuZCexnFSpr5FQk/rHM6s1CVIMsfUMZV/sY6ChRpZonLdhNj/khRFv/VKBWYbPICt2QvG6kKC3WlshXrJWsihfeF9jjZ2wKR3Nxvb7FaoW+uoFFoPAMqppHVKCnYbH1C+xdnXKjmOGgvut+FTPiSxWIHyLIYBrreMXCxXZboS3HBX1beG01nSkiaaSbUYPYw=
  app: 
    master: create-issue-branch
    staging: create-issue-branch-staging
