language: node_js
cache:
  directories:
    - $HOME/.npm

node_js:
  - lts/*

notifications:
  email:
    on_success: never

after_success:
    - echo "$TRAVIS_BRANCH"
    - echo "$TRAVIS_PULL_REQUEST"
    - test "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" = "false" && \
      sh .travis/deploy_heroku.sh
