name: App Stats
on:
  push:
    branches:
      - master

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/app-stats-action@v1.x
        id: stats
        with:
          id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - run: 'pwd'
      - run: 'ls -l'
      - run: 'echo "{\"installations\": ${{ steps.stats.outputs.installations }}, \"repositories\": ${{ steps.stats.outputs.repositories }}, \"suspended\": ${{ steps.stats.outputs.suspended_installations }}, \"popular\": ${{ steps.stats.outputs.popular_repositories }} }" > stats.json'
      - run: 'ls -l'
      - name: Commit GitHub Action distribution
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add static/stats.json
          git commit -m "Build by GitHub Actions" || true
        if: job.status == 'success'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        if: job.status == 'success'

