name: CICD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      CI: true
      
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn install
    - run: yarn test
    - run: yarn run lint
    - name: Deploy master to Heroku
      env:
        HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
      run: git push https://heroku:$HEROKU_AUTH_TOKEN@git.heroku.com/create-issue-branch.git origin/master:master
      if: github.ref == 'refs/heads/master' && job.status == 'success'
    - name: Deploy staging to Heroku
      env:
        HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
      run: git push https://heroku:$HEROKU_AUTH_TOKEN@git.heroku.com/create-issue-branch-staging.git staging
      if: github.ref == 'refs/heads/staging' && job.status == 'success'
